### ISSUE TITLE
can't compile - threads issue

### ISSUE THREAD

**Issue by SomeFixItDude** [xun-project/UltraNote#1]
Hi I am trying to compile on debian stretch, and following the instructions I get can not find threads from boost. 

-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Readline: /usr/include
-- Found readline library at: /usr
-- Looking for pthread.h
-- Looking for pthread.h - not found
CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.7/Modules/FindThreads.cmake:212 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /usr/share/cmake-3.7/Modules/CMakeFindDependencyMacro.cmake:55 (find_package)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1476 (find_dependency)
  CMakeLists.txt:150 (find_package)

How should I proceed to get a successful compile?

**Comment by UltraNote** [comment]
Which Cmake and boost versions you are using?

**Comment by UltraNote** [comment]
Solved in version 1.0.11 https://github.com/xun-project/UltraNote/releases/tag/v1.0.11 please update your source.
