### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by lesstilt** [xun-project/UltraNote#1]
I have followed all the instructions in the readme to compile UltraNote.  
gcc is version 4.8.4, cmake is version 2.8.12.2, and boost is version 1.55.  OS is Ubuntu 14.04 LTS.
I have even tried using gcc 4.7.3 and cmake 2.8.6 with the same error.

This is the error I get:
[ 65%] Building CXX object tests/CMakeFiles/CoreTests.dir/CoreTests/ChaingenMain.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[3]: *** [tests/CMakeFiles/CoreTests.dir/CoreTests/ChaingenMain.cpp.o] Error 4
make[3]: Leaving directory `/UltraNote/build/release'
make[2]: *** [tests/CMakeFiles/CoreTests.dir/all] Error 2
make[2]: Leaving directory `/UltraNote/build/release'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/UltraNote/build/release'
make: *** [build-release] Error 2

**Comment by nesterow** [comment]
Best way to build cpp applications is to use Docker or a virtual machine. Here is my Dockerfile:
```ruby
FROM debian:jessie
RUN mkdir -p /opt/app/build
WORKDIR /opt/app/build
COPY UltraNote /opt/app
RUN apt-get update && apt-get install -y \
  g++ \
  cmake \
  libboost-system1.55-dev \
  libboost-filesystem1.55-dev \
  libboost-thread1.55-dev \
  libboost-date-time1.55-dev \
  libboost-chrono1.55-dev \
  libboost-regex1.55-dev \
  libboost-serialization1.55-dev \
  libboost-program-options1.55-dev \
  libboost-coroutine1.55-dev \
  libboost-context1.55-dev \
  libboost1.55-dev
RUN cmake .. 
WORKDIR /opt/app
RUN make build-static
WORKDIR /opt/app/build
```
All executables will be in `/opt/app/build/static`
This build method doesn't link libboost statically so you will need to install libboost1.55-all on the system where you intend to run daemons. Or you can copy all neded `*.so` files and set `LD_LIBRARY_PATH` before running.

If you don't use docker then follow same steps in a virtual machine.

**Comment by lesstilt** [comment]
Ok, I got it working with Ubuntu 16.04.  Even got the pool software to load.  Question... Does the pool software work with ultranotewallet or with walletd?

**Comment by nesterow** [comment]
It suppose to work with `ultranotewallet` rpc. `walled` is a daemon for exchanges.
