### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by euskoblockchain** [xun-project/UltraNote#1]
Im trying to build Ultranote on windows and im stuck in this step:

MSBuild UltraNote.sln /p:Configuration=Release /m

error MSB4126 : Configuration "Release|x64" not valid

Tried with /p:Platform="Any CPU" and back to the same error

**Comment by UltraNote** [comment]
Try building UltraNote.sln using MSVC 2017 or 2019

**Comment by euskoblockchain** [comment]
Worked building with the MSVC 2017 directly and not with the command promp

**Comment by UltraNote** [comment]
Both should work fine. Never had a problem building it.
