### ISSUE TITLE
wallet cant be access it

### ISSUE THREAD

**Issue by velicumugur** [xun-project/UltraNote#10]
i generate couple wallets  using ultranotewallet

i build a pool that fail to make payments and i try to use walletd with one of this wallet file , that i can't access it anymore using ultranotewallet , i get wrong password , that file can be access it with walletd with same password that ultranotewallet refuse to use it... how can i get money from this wallet without curl?

pool also fail to make payment, walletd logs say unknow method transfer
xun pool it's build with methode getbalance walletd require getBalance  , etc.

**Comment by UltraNote** [comment]
I have no idea what you are trying to do, Please join our discord and we will try to help you.
https://discord.gg/xyHw8vE
