### ISSUE TITLE
explorer is on wrong chain.

### ISSUE THREAD

**Issue by sebseb7** [xun-project/UltraNote#11]
current github master cannot sync that block

http://explorer.ultranote.org/?hash=9db4950326d3bfc8d6db40d22017a0afd0ef69044a6ae807b8c3a43c2042d9c0#blockchain_block

17:35:39.390741 INFO Block with id: <9db4950326d3bfc8d6db40d22017a0afd0ef69044a6ae807b8c3a43c2042d9c0>
17:35:39.390741 INFO  for alternative chain, have not enough proof of work: <d6db6da4178d642ec9a0fad0f6404676d27564f0c9697f5df29453bd04000000>
17:35:39.390741 INFO  expected difficulty: 1119258393
17:35:56.852591 INFO Block with id: <9db4950326d3bfc8d6db40d22017a0afd0ef69044a6ae807b8c3a43c2042d9c0>
17:35:56.852591 INFO  for alternative chain, have not enough proof of work: <d6db6da4178d642ec9a0fad0f6404676d27564f0c9697f5df29453bd04000000>
17:35:56.852591 INFO  expected difficulty: 1119258393
17:36:08.674330 INFO Block with id: <9db4950326d3bfc8d6db40d22017a0afd0ef69044a6ae807b8c3a43c2042d9c0>
17:36:08.674330 INFO  for alternative chain, have not enough proof of work: <d6db6da4178d642ec9a0fad0f6404676d27564f0c9697f5df29453bd04000000>
17:36:08.674330 INFO  expected difficulty: 1119258393
17:36:17.951341 INFO Block with id: <9db4950326d3bfc8d6db40d22017a0afd0ef69044a6ae807b8c3a43c2042d9c0>
17:36:17.951341 INFO  for alternative chain, have not enough proof of work: <d6db6da4178d642ec9a0fad0f6404676d27564f0c9697f5df29453bd04000000>
17:36:17.951341 INFO  expected difficulty: 1119258393

**Comment by echa** [comment]
Using the chain from https://ultranote.org/UltraNote-Blocks.zip and resetting the wallet worked.
