### ISSUE TITLE
walletd shoud not bind to 0.0.0.0 by default

### ISSUE THREAD

**Issue by sebseb7** [xun-project/UltraNote#2]
127.0.0.1 is a more sane default

**Comment by nesterow** [comment]
Thanks.
Normally payment service (`walletd`) suppose to run in a container or a virtual environment.  So a consumer can reach it using container ip on the host machine. I wouldn't recommend to run everything in one environment.

**Comment by sebseb7** [comment]
"Normally"

regarding security questions, especially when "money" comes into play. The worst case scenario is the "normal", what you plan for.

"Configuring firewall rules for 127.0.0.1 can be tricky"

still no need to open it up to the world by default.

**Comment by nesterow** [comment]
@sebseb7 
Before writing such comments you should probably learn some theory. "Normally" no one exposes virtual bridge interfaces to the world.  "the worst case scenario" is actually running everything out of sandbox listening on 127.0.0.1

"still no need to open it up to the world by default." 
Still no need avoiding configuration "especially when money comes into play". 

Here some links for you to read, also "regarding security questions" :

_An old tutorial on creating dummy interfaces:_
http://www.pocketnix.org/posts/Linux%20Networking:%20Dummy%20Interfaces%20and%20Virtual%20Bridges

_Official Docker documentation:_
https://docs.docker.com/engine/userguide/networking

**Comment by sebseb7** [comment]
"Before writing such comments you should probably learn some theory."

Before starting a coin you should learn the basics. no block for 15 hours, you coin is dead anyway.
