### ISSUE TITLE
blockchain sync error

### ISSUE THREAD

**Issue by oslet** [xun-project/UltraNote#21]
Hi dev team:
    my env:   ubuntu 16.04  amd64
     branch: master
   last commit: b8775803b8d7c5f03c8023ea0515b4582fc977b8

When I build from source and run ultranoted, the blockchain is not sync, some like this
![_004](https://user-images.githubusercontent.com/1573303/42094648-06b31f38-7be3-11e8-8806-76e1de5c0361.png)

Help

**Comment by UltraNote** [comment]
You need to clear the blocks from the file .UltraNote and then run the daemon again. You can download a copy of the blockchain on our website https://ultranote.org
