### ISSUE TITLE
cmake pthread.h error

### ISSUE THREAD

**Issue by cheebeez** [xun-project/UltraNote#8]
> Looking for pthread.h - not found

Debian with latest versions of cmake/boost/gcc =(

Need compiled release.
Thanks.

**Comment by UltraNote** [comment]
Which boost version do you have?

**Comment by cheebeez** [comment]
Version: 1.62.0.1

**Comment by UltraNote** [comment]
Could you please install libboost version 1.0.58 because even if I send you a compiled source it won't work with your boost version.
We will try to fix our Cmake build as soon as possible.

**Comment by nesterow** [comment]
It has to compile with boost 1.62. 
I compiled it with GCCv6 and boost 1.62 on newer debian versions and Arch Linux.
Current cmake config doesn't handle some gcc versions yet.

You can try to downgrade gcc/g++ with `sudo update-alternatives`:
```sh
#install available versions
sudo apt install gcc-4.9 g++-4.9

sudo update-alternatives --remove-all gcc
sudo update-alternatives --remove-all g++

#Add alternatives for your GCC versions
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7.1 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.6
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8

# pick GCC version
sudo update-alternatives --config gcc
```

Also some gcc versions might need `libpthread-stubs0` package
```sh
sudo apt install libpthread-stubs0-dev
```

**Comment by cheebeez** [comment]
Thanks!
