### ISSUE TITLE
what is this function? 

### ISSUE THREAD

**Issue by Goldeneum** [xun-project/UltraNote#9]
void addTTLToExtra(const u_int64_t& ttl, std::string& extra) {
  std::vector<uint8_t> extraVector;
  CryptoNote::appendTTLToExtra(extraVector, ttl);
  std::copy(extraVector.begin(), extraVector.end(), std::back_inserter(extra));

in https://github.com/xun-project/UltraNote/blob/62616ef6ad4f59ef7ce38732da25973bf892c4de/src/PaymentGate/WalletService.cpp

line 156.. i cant find it in cryptonote original code...
its give me errors when compiling the code.. undiffined u_int64_t and ttl !

**Comment by UltraNote** [comment]
What are you trying to do? Why it fails to compile for you?
